setwd(dirname(parent.frame(2)$ofile))
test_x <- rnorm(100)
test_y <- rnorm(100)
print(bubble_plot(test_x, test_y))
print(bubble_plot(test_x, test_y, show_counts = TRUE))
print(bubble_plot(males[1:500], females[1:500], show_counts = FALSE))
the_plot <- bubble_plot(males[1:500], females[1:500])
the_plot <- the_plot + xlab("Males") + ylab("Females")
print(the_plot)
